### ISSUE TITLE
测试运行tandem报错

### ISSUE THREAD

**Issue by sangzhe** [baimingze/project1#3]
报错提示

> [sangzhe@localhost mrtandem_bin]$ ./tandem gpm_input.xml
> ./tandem: error while loading shared libraries: libboost_serialization.so.1.57.0: cannot open shared object file: No such file or directory

**Comment by baimingze** [comment]
我上传了库文件，请下载到/usr/lib64 或者/usr/lib试试

**Comment by sangzhe** [comment]
已经运行了tandem，参数文件需要修改一下
- 目录下的gpm_input.xml和gpm_default.xml都要改为input.xml和default_input.xml
- taxonomy.xml文件里的`<taxon label>`这个标签似乎必须是`<taxon label = “yeast”>`而不能是原来的`<taxon label=“protein_database”>.`
- taxonomy.xml中似乎只能有一对`<taxon label = “yeast”>` `</taxon>`,URL在这之间。原来有两对就运行不了

**Comment by baimingze** [comment]
我没有修改也能运行，它们的运行结果有什么区别呢？

```
[mingze@localhost bin]$ ./tandem tandem_params.xml

X! TANDEM 2010.10.01.1 (LabKey, Insilicos and ISB)

Loading spectra . loaded.
Spectra matching criteria = 653
Pluggable scoring enabled.
Starting threads . started.
Computing models:
        12      sequences modelled = 1 ks
Model refinement:
Creating report:
        initial calculations  ..... done.
        sorting  ..... done.
        finding repeats ..... done.
        evaluating results ..... done.
        calculating expectations ..... done.
        writing results ..... done.

Valid models = 9


[mingze@localhost bin]$ 
```

**Comment by sangzhe** [comment]
Spectra matching criteria 不同，最后结果除了有Valid models 还有unique models ，estimated false positives。
是输入文件不同造成的。我输入的是gpm_input.xml，在这里taxon label是yeast ，所以taxonomy文件里也要改为yeast。
然后我在x!tandem网页上看到，gpm_input.xml代表运行tandem的最小输入文件。gmp_default_input.xml应该是代表输入最齐全的文件，之前没注意到这点

**Comment by sangzhe** [comment]
```
[root@server-200 mrtandem_bin]# ./tandem tandem_params.xml
./tandem: error while loading shared libraries: /lib64/libboost_serialization.so.1.57.0: ELF file OS ABI invalid
```

在服务器上运行tandem出现这个问题

**Comment by baimingze** [comment]
库需要重新编译，我下班后弄一下

**Comment by baimingze** [comment]
在局域网机器上试了一下，需要改动的地方很多，局域网机器的版本太低了。不方便。

我建议放弃这个方案。

我觉得这个方法可以试一试：
把你的机器上目前可以运行的 hadoop文件夹，mrtandem文件夹打包发给我，我试一试。
以排除某个不起眼地方配置不同的原因，你觉得如何？
