### ISSUE TITLE
Questions about spectrum file

### ISSUE THREAD

**Issue by sangzhe** [baimingze/project1#7]
1. xtandem supports DTA, PKL or MGF files,each file contains more than one spectrum.
   I think the information need to be classified when divided , but I'm not familiar with spectrum file.
   Whether one file contains several results of peptides , which means each spectrum is a result of a peptide?
2. I wonder if xtandem calculates the value through mass—m/z pair of fragment ?
   Does peptide mass  and charge matter ?

**Comment by baimingze** [comment]
Good questions!

> xtandem supports DTA, PKL or MGF files,each file contains more than one spectrum.
>  I think the information need to be classified when divided , but I'm not familiar with spectrum file.
> Whether one file contains several results of peptides , which means each spectrum is a result of a peptide?

I suggest we only use MGF now. And you can splice the MGF by "BEGIN IONS" and "END IONS". You just need to make sure the splice only happen between  last "END IONS" and next "BEGIN".

>    I wonder if xtandem calculates the value through mass—m/z pair of fragment ?
>     Does peptide mass and charge matter ?

This is about the calculation in the C++ code. I think we can wrap it as a black box, without understand the detail at first.

**Comment by sangzhe** [comment]
> I understand that we need to split the spectrum according to "BEGIN IONS" and "END IONS"，but I think  such a slice still need to be split into key/value pair for mapreduce，and the keys from one slice are assigned to one reducer task.
> Or is it possible to consider a slice(contains several lines) as a key?

Is there any special restriction on key? I guess the simplest way is like this:
|1|2|3|4|....
but I am not sure will it work or not.

**Comment by sangzhe** [comment]
I just used tandem to do search with one peptide information in MGF file.
I now understand that to launch tandem to execute, a slice(between "BEGIN IONS" and "END IONS") can not be divided anymore.I previously thought tandem could run with only a fragment of a peptide.
